### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by arturino009** [Lachrymatory/MapNotify#4]
It fails to compile on launch. 
The line:
var awakeComp = serverData.AwakenedAreas;
seems to be the main issue, as the ServerData memory object in ExileCore doesn't contain the variable AwakenedAreas anymore.

I managed to compile the plugin by removing this variable (and the only place it is used), but it still doesn't seem to work, as it is not drawing any overlays.
I can't really pinpoint the main issue, as there dont seem to be any errors logged.

**Comment by Lachrymatory** [comment]
Offsets weren't updated for the area data, just added it to this instead for ease.
Working on latest PoEHelper.zip in any case.

**Comment by arturino009** [comment]
So does the plugin actually work? It compiles fine, but there still aren't any overlays. Am I supposed to press some button? It seems like it's not really detecting the map. The debug feature doesn't list any mods for the map on hower. I'm using ExileAPI from Queuete btw.
