### ISSUE TITLE
Queuete's HUD not supported

### ISSUE THREAD

**Issue by arturino009** [Lachrymatory/MapNotify#5]
So does the plugin actually work? It compiles fine, but there still aren't any overlays. Am I supposed to press some button? It seems like it's not really detecting the map. The debug feature doesn't list any mods for the map on hower. I'm using ExileAPI from Queuete btw.

**Comment by Lachrymatory** [comment]
From some cursory testing, Queuete's uihover element is completely broken. Get him to fix that and add back the devtree plugin and I might get it working.

**Comment by arturino009** [comment]
Well that makes sense. Which tool are you using then for it to work?

**Comment by arturino009** [comment]
Well, I did it myself and fixed Queuete's UIHover, so this plugin works now.
