### ISSUE TITLE
Not working with Queuetes fork of ExileAPI

### ISSUE THREAD

**Issue by Violet-Vibes** [Lachrymatory/MapNotify#7]
Getting "unknown region" on maps and an error

`2021-04-21 00:49:37.521 +02:00 [ERR] Map Mod Notifications, Initialise -> System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid MapNotify.MapNotify.BuildRegions()
   vid MapNotify.MapNotify.Initialise()
   vid ExileCore.Shared.PluginWrapper.pluginInitialise() i /buddy/exileapi/Core/Shared/PluginWrapper.cs:rad 130
   vid ExileCore.Shared.PluginWrapper.Initialise(GameController _gameController) i /buddy/exileapi/Core/Shared/PluginWrapper.cs:rad 69
2021-04-21 00:49:41.701 +02:00 [ERR] Map Mod Notifications, Initialise -> System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid MapNotify.MapNotify.BuildRegions()
   vid MapNotify.MapNotify.Initialise()
   vid ExileCore.Shared.PluginWrapper.pluginInitialise() i /buddy/exileapi/Core/Shared/PluginWrapper.cs:rad 130
   vid ExileCore.Shared.PluginWrapper.<>c__DisplayClass41_0.<Initialise>b__0(Object obj, Boolean value) i /buddy/exileapi/Core/Shared/PluginWrapper.cs:rad 95`

**Comment by Lachrymatory** [comment]
Queuete's map component has broken offsets, unless it returns a non-null WorldArea it'll be broken.

**Comment by DaxxTrias** [comment]
Quete's build had a PR to fix some stuff with atlas node. It seems to have fixed this (or at least my build isn't spitting out errors anymore)

You can probably close this ticket now sir.
